SHELL := /bin/bash

.PHONY: up down logs ps

up:
	bash scripts/dev-up.sh

down:
	bash scripts/dev-down.sh

logs:
	docker compose -f deploy/docker-compose.dev.yml logs -f --tail=200

ps:
	docker compose -f deploy/docker-compose.dev.yml ps
